### ISSUE TITLE
문서 .eslintrc.js 설정부분 오탈자

### ISSUE THREAD

**Issue by yeonjuan** [nhn/tui.eslint.config#7]
README.md 의 [.eslintrc.js 설정 예제](https://github.com/nhn/tui.eslint.config#rules-and-syntax) ` module.exports = `부분에 `{` 가 하나 빠졌습니다.

**Comment by jinwoo-kim-nhn** [comment]
@yeonjuan 감사합니다. 확인이 늦었네요. 바로 수정하였습니다.
